"""Fixed bootstrap schema for the original community tables.

Do not import application models here: later migrations create their own tables.
Add future changes in new revisions instead of regenerating this snapshot.
"""

TABLE_NAMES = [
    "categories",
    "mcp_categories",
    "users",
    "mcp_servers",
    "posts",
    "bookmarks",
    "comments",
    "files",
    "likes",
    "mcp_install_guides",
    "mcp_reviews",
    "mcp_tools",
    "playground_usages",
    "notifications"
]

SCHEMA_STATEMENTS = [
    "CREATE TABLE IF NOT EXISTS categories (\n\tid SERIAL NOT NULL, \n\tname VARCHAR(50) NOT NULL, \n\tdescription VARCHAR(200), \n\tslug VARCHAR(50) NOT NULL, \n\ticon VARCHAR(100), \n\t\"order\" INTEGER, \n\tis_active BOOLEAN, \n\tPRIMARY KEY (id), \n\tUNIQUE (slug)\n)",
    "CREATE INDEX IF NOT EXISTS ix_categories_id ON categories (id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_categories_name ON categories (name)",
    "CREATE TABLE IF NOT EXISTS mcp_categories (\n\tid SERIAL NOT NULL, \n\tname VARCHAR(50) NOT NULL, \n\tslug VARCHAR(50) NOT NULL, \n\tdescription VARCHAR(200), \n\ticon VARCHAR(50), \n\tdisplay_order INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id)\n)",
    "CREATE INDEX IF NOT EXISTS ix_mcp_categories_id ON mcp_categories (id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_mcp_categories_name ON mcp_categories (name)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_mcp_categories_slug ON mcp_categories (slug)",
    "CREATE TABLE IF NOT EXISTS users (\n\tid SERIAL NOT NULL, \n\temail VARCHAR(255) NOT NULL, \n\tusername VARCHAR(50) NOT NULL, \n\thashed_password VARCHAR(255) NOT NULL, \n\thas_local_password BOOLEAN DEFAULT true NOT NULL, \n\temail_verified BOOLEAN DEFAULT false NOT NULL, \n\temail_verified_at TIMESTAMP WITH TIME ZONE, \n\tis_admin BOOLEAN, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tprofile_image_url VARCHAR(500), \n\tbio VARCHAR(200), \n\texperience_points INTEGER, \n\tlevel INTEGER, \n\tbadge VARCHAR(50), \n\tPRIMARY KEY (id)\n)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)",
    "CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username ON users (username)",
    "CREATE TABLE IF NOT EXISTS mcp_servers (\n\tid SERIAL NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tslug VARCHAR(100) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tshort_description VARCHAR(300), \n\tgithub_url VARCHAR(500), \n\tgithub_stars INTEGER, \n\tgithub_readme TEXT, \n\tgithub_last_synced TIMESTAMP WITH TIME ZONE, \n\tinstall_command TEXT, \n\tpackage_name VARCHAR(200), \n\tis_featured BOOLEAN, \n\tis_verified BOOLEAN, \n\tdemo_video_url VARCHAR(500), \n\tshowcase_data TEXT, \n\tavg_rating FLOAT, \n\treview_count INTEGER, \n\tcategory_id INTEGER, \n\tcreated_by INTEGER, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(category_id) REFERENCES mcp_categories (id), \n\tFOREIGN KEY(created_by) REFERENCES users (id)\n)",
    "CREATE INDEX IF NOT EXISTS ix_mcp_servers_id ON mcp_servers (id)",
    "CREATE INDEX IF NOT EXISTS ix_mcp_servers_name ON mcp_servers (name)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ix_mcp_servers_slug ON mcp_servers (slug)",
    "CREATE TABLE IF NOT EXISTS posts (\n\tid SERIAL NOT NULL, \n\ttitle VARCHAR(255) NOT NULL, \n\tcontent TEXT NOT NULL, \n\tviews INTEGER, \n\tuser_id INTEGER NOT NULL, \n\tcategory_id INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tis_pinned BOOLEAN, \n\tis_featured BOOLEAN, \n\tpinned_order INTEGER, \n\tpost_type VARCHAR(20) DEFAULT 'NORMAL' NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(category_id) REFERENCES categories (id)\n)",
    "CREATE INDEX IF NOT EXISTS ix_posts_category_id ON posts (category_id)",
    "CREATE INDEX IF NOT EXISTS ix_posts_created_at ON posts (created_at)",
    "CREATE INDEX IF NOT EXISTS ix_posts_id ON posts (id)",
    "CREATE INDEX IF NOT EXISTS ix_posts_is_pinned ON posts (is_pinned)",
    "CREATE INDEX IF NOT EXISTS ix_posts_pinned_order ON posts (pinned_order)",
    "CREATE INDEX IF NOT EXISTS ix_posts_post_type ON posts (post_type)",
    "CREATE TABLE IF NOT EXISTS bookmarks (\n\tid SERIAL NOT NULL, \n\tpost_id INTEGER NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tCONSTRAINT unique_post_user_bookmark UNIQUE (post_id, user_id), \n\tFOREIGN KEY(post_id) REFERENCES posts (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE INDEX IF NOT EXISTS ix_bookmarks_created_at ON bookmarks (created_at)",
    "CREATE INDEX IF NOT EXISTS ix_bookmarks_id ON bookmarks (id)",
    "CREATE INDEX IF NOT EXISTS ix_bookmarks_post_id ON bookmarks (post_id)",
    "CREATE INDEX IF NOT EXISTS ix_bookmarks_user_id ON bookmarks (user_id)",
    "CREATE TABLE IF NOT EXISTS comments (\n\tid SERIAL NOT NULL, \n\tcontent TEXT NOT NULL, \n\tpost_id INTEGER NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(post_id) REFERENCES posts (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)",
    "CREATE INDEX IF NOT EXISTS ix_comments_created_at ON comments (created_at)",
    "CREATE INDEX IF NOT EXISTS ix_comments_id ON comments (id)",
    "CREATE INDEX IF NOT EXISTS ix_comments_post_id ON comments (post_id)",
    "CREATE INDEX IF NOT EXISTS ix_comments_user_id ON comments (user_id)",
    "CREATE TABLE IF NOT EXISTS files (\n\tid SERIAL NOT NULL, \n\tfilename VARCHAR(255) NOT NULL, \n\toriginal_filename VARCHAR(255) NOT NULL, \n\tfile_path VARCHAR(500) NOT NULL, \n\tfile_size INTEGER NOT NULL, \n\tmime_type VARCHAR(100), \n\tpost_id INTEGER NOT NULL, \n\tuploaded_by INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(post_id) REFERENCES posts (id) ON DELETE CASCADE, \n\tFOREIGN KEY(uploaded_by) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE INDEX IF NOT EXISTS ix_files_id ON files (id)",
    "CREATE TABLE IF NOT EXISTS likes (\n\tid SERIAL NOT NULL, \n\tpost_id INTEGER NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT unique_post_user_like UNIQUE (post_id, user_id), \n\tFOREIGN KEY(post_id) REFERENCES posts (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE INDEX IF NOT EXISTS ix_likes_id ON likes (id)",
    "CREATE TABLE IF NOT EXISTS mcp_install_guides (\n\tid SERIAL NOT NULL, \n\tclient_name VARCHAR(50) NOT NULL, \n\tconfig_json TEXT NOT NULL, \n\tinstructions TEXT, \n\tserver_id INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(server_id) REFERENCES mcp_servers (id) ON DELETE CASCADE\n)",
    "CREATE INDEX IF NOT EXISTS ix_mcp_install_guides_id ON mcp_install_guides (id)",
    "CREATE TABLE IF NOT EXISTS mcp_reviews (\n\tid SERIAL NOT NULL, \n\trating INTEGER NOT NULL, \n\tcontent TEXT, \n\tserver_id INTEGER NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tCONSTRAINT unique_server_user_review UNIQUE (server_id, user_id), \n\tFOREIGN KEY(server_id) REFERENCES mcp_servers (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    "CREATE INDEX IF NOT EXISTS ix_mcp_reviews_id ON mcp_reviews (id)",
    "CREATE TABLE IF NOT EXISTS mcp_tools (\n\tid SERIAL NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tdescription TEXT, \n\tinput_schema TEXT, \n\tsample_output TEXT, \n\tserver_id INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(server_id) REFERENCES mcp_servers (id) ON DELETE CASCADE\n)",
    "CREATE INDEX IF NOT EXISTS ix_mcp_tools_id ON mcp_tools (id)",
    "CREATE INDEX IF NOT EXISTS ix_mcp_tools_name ON mcp_tools (name)",
    "CREATE TABLE IF NOT EXISTS playground_usages (\n\tid SERIAL NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\tserver_id INTEGER, \n\ttool_name VARCHAR(100) NOT NULL, \n\texecution_time_ms FLOAT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, \n\tFOREIGN KEY(server_id) REFERENCES mcp_servers (id) ON DELETE SET NULL\n)",
    "CREATE INDEX IF NOT EXISTS ix_playground_usages_id ON playground_usages (id)",
    "CREATE TABLE IF NOT EXISTS notifications (\n\tid SERIAL NOT NULL, \n\tuser_id INTEGER NOT NULL, \n\ttype VARCHAR(50) NOT NULL, \n\tcontent TEXT NOT NULL, \n\trelated_post_id INTEGER, \n\trelated_comment_id INTEGER, \n\tis_read BOOLEAN, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, \n\tFOREIGN KEY(related_post_id) REFERENCES posts (id) ON DELETE CASCADE, \n\tFOREIGN KEY(related_comment_id) REFERENCES comments (id) ON DELETE CASCADE\n)",
    "CREATE INDEX IF NOT EXISTS ix_notifications_created_at ON notifications (created_at)",
    "CREATE INDEX IF NOT EXISTS ix_notifications_id ON notifications (id)",
    "CREATE INDEX IF NOT EXISTS ix_notifications_is_read ON notifications (is_read)",
    "CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications (user_id)"
]
